services:
  vectorizer:
    build:
      context: .
      dockerfile: Dockerfile.vector
    volumes:
      - ./scraped_links:/app/scraped_links
    environment:
      - PYTHONUNBUFFERED=1
    # Commande à exécuter avec les clés API
    # Remplacez YOUR_PINECONE_API_KEY et YOUR_OPENAI_API_KEY par vos clés réelles
    command: [
      "--pinecone-api-key", "${PINECONE_API_KEY}",
      "--openai-api-key", "${OPENAI_API_KEY}",
      "--pinecone-index", "scraped-sites",
      "--chunk-size", "1000",
      "--chunk-overlap", "200"
    ]
